trigger:
- main

pool:
  name: MySelfHostedAgentPool
  demands: npm

variables:
  buildConfiguration: 'Release'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(System.DefaultWorkingDirectory)/angular-app'
  displayName: 'Install Angular dependencies'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
  displayName: 'Restore .NET dependencies'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'Build .NET application'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(System.DefaultWorkingDirectory)/angular-app'
  displayName: 'Install Angular dependencies'

- task: Npm@1
  inputs:
    command: 'run'
    workingDir: '$(System.DefaultWorkingDirectory)/angular-app'
    arguments: 'build --prod'
  displayName: 'Build Angular application'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(System.DefaultWorkingDirectory)/angular-app/dist'
    artifactName: 'angular-app'
  displayName: 'Publish Angular artifacts'

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(System.DefaultWorkingDirectory)/dotnet-app/bin/$(buildConfiguration)/net5.0'
    artifactName: 'dotnet-app'
  displayName: 'Publish .NET artifacts'
